notice:
  discussion:
    rules:
      - # If a discussion is created in the Announcements or Reviews
        # category, apply the notice label
        category:
          - Announcements
          - Consensus Building
        action: [created, category_changed]
        then: [label_notice]
      - # If the notice or vote/open label is applied,
        # send email
        action: [labeled]
        label:
          - notice
          - "vote/open"
        then: [email_activity]
      - # If the vote/done label is applied, remove the vote/open label
        action: [labeled]
        label: ["vote/done"]
        then: [label_done]
  pull_request:
    rules:
      - # If a pull request modifies bylaws or policies
        # apply the notice label
        action:
          - opened
          - edited
          - closed
        paths:
          - bylaws/*
          - policies/*
        then: [label_notice]
      - # If a pull request is labeled with notice,
        # send an email to email_activity
        action: [labeled]
        label: [notice]
        then: [email_activity]
  actions:
    label_notice: [notice]
    label_done: ["!vote/open"]
    email_activity:
      address:
      - announce@commonhaus.org
      - cf-council@commonhaus.org

voting:
  exclude_login:
    - commonhaus-bot
  error_email_address:
    - automation@commonhaus.org
  status:
    badge: https://www.commonhaus.org/votes/{{repoName}}/{{number}}.svg
    page: https://www.commonhaus.org/votes/{{repoName}}/{{number}}.html
