notice:
  discussion_comment:
    rules:
      - # If a comment is added to a notice discussion by a Commonhaus member (avoid spam),
        # send it to the EGC list
        action: [created]
        label:
        - notice
        - "vote/open"
        - "vote/done"
        member:
          - commonhaus
        then: [egc]
  issue_comment:
    rules:
      - # If a comment is added to a notice PR by a Commonhaus member (avoid spam),
        # send it to the EGC list
        action: [created]
        label:
        - notice
        - "vote/open"
        - "vote/done"
        then: [egc]
  discussion:
    rules:
      - # If a discussion is created in Announcements or Consensus Building
        # and it already has the notice label, send an email
        # Note: Announcements & Consensus Building are restricted to Maintainers
        category:
          - Announcements
          - Consensus Building
        label: [notice]
        action: [created]
        then: [announce, egc]
      - # If a discussion is created in or moved to Announcements or Consensus Building
        # and it does not have the notice label, apply the notice label
        category:
          - Announcements
          - Consensus Building
        label: ["!notice"]
        action: [created, category_changed]
        then: [apply_notice]
      - # If the notice label is applied, send email to announce and egc lists
        action: [labeled]
        label_change:
          - notice
        then: [announce, egc]
      - # If the vote/open, or vote/done label is applied, send email to announce
        action: [labeled]
        label_change:
          - "vote/open"
          - "vote/done"
        then: [announce]
      - # If the vote/done label is applied, remove the vote/open label
        action: [labeled]
        label_change: ["vote/done"]
        then: [remove_open]
  pull_request:
    rules:
      - # If a pull request modifies bylaws or policies
        # and the PR creator is a member of the organization
        # and it does not have the notice label, 
        # apply the notice label
        action:
          - opened
          - edited
          - closed
        paths:
          - agreements/project-contribution/*
          - bylaws/*
          - policies/*
        label: ["!notice"]
        member:
          - commonhaus
        then: [apply_notice]
      - # If the notice label is applied, send email to announce and egc lists
        action: [labeled]
        label_change:
          - notice
        then: [announce, egc]
      - # If the vote/open, or vote/done label is applied, send email to announce
        action: [labeled]
        label_change:
          - "vote/open"
          - "vote/done"
        then: [announce]
      - # If the vote/done label is applied, remove the vote/open label
        action: [labeled]
        label_change: ["vote/done"]
        then: [remove_open]
  actions:
    apply_notice: [notice]
    remove_open: ["!vote/open"]
    announce:
      address:
      - announce@commonhaus.org
    egc:
      address:
      - cf-egc@commonhaus.org

voting:
  vote_threshold:
    commonhaus/cf-egc: twothirds
  alternates:
    - source: CONTACTS.yaml
      repo: commonhaus/foundation
      mapping:
        - field: project
          primary:
            data: egc
            team: commonhaus/cf-egc
          secondary:
            data: egc-second
            team: commonhaus/cf-egc-second
  exclude_login:
    - commonhaus-bot
  error_email_address:
    - automation@commonhaus.org
  managers:
    - "@commonhaus/cf-council"
  status:
    badge: https://www.commonhaus.org/votes/{{repoName}}/{{number}}.svg
    page: https://www.commonhaus.org/votes/{{repoName}}/{{number}}.html
