teamMembership:
  - dryRun: true
    source:
      repository: commonhaus/foundation
      filePath: CONTACTS.yaml
    defaults:
      field: login
      ignoreUsers:
        - commonhaus-bot
    pushMembers:
      cf-council:
        teams:
          - commonhaus/cf-council
          - commonhaus-ops/admin
      egc:
        teams:
          - commonhaus/cf-egc
      egc-second:
        teams:
          - commonhaus/cf-egc-second
      coc-panel:
        teams:
          - commonhaus/coc-panel
      advisory-board:
        preserveUsers:
          - ashni-mehta
        teams:
          - commonhaus/advisory-board

emailNotifications:
  errors:
    - automation@commonhaus.org
  dryRun:
    - test@commonhaus.dev
  audit:
    - automation@commonhaus.org