labels: ["notice"]
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Announcements will be forwarded to the website and to the announcements mailing list.
        > - Title: Keep the title short and sweet. If action is required say so, and say when.
  - type: textarea
    attributes:
      label: Announcement
      description: Be descriptive but concise. Links help. Required actions should be easy to find.
      placeholder: "The next CFC Meeting will be on on Wed, 22 December 2030.\n\nAgenda: ..."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > SEO description helps with search engine discovery. It should be 200 characters or less,
        > and be descriptive in nature (don't use Learn, or Explore, or.. ). AI can be good for this,
        > but it needs to be coached to avoid "Learn...", "Explore..." sentence construction.
  - type: textarea
    attributes:
      label: "<!-- SEO Text as HTML comment (hidden) -->"
      description: Replace "..." with description/summary in 200 chars or less
      value: |
        <!-- meta::description ... -->
