name: Push discussions to commonhaus.github.io

on:
  discussion:
  workflow_dispatch:

jobs:
  update-discussions:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'commonhaus/foundation-draft'
    steps:
    - name: Bump website
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_PUBLISH_PAT }}
      run: |
        gh workflow run -R commonhaus/commonhaus.github.io gh-pages.yml
