name: Check Markdown Links

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.mlc_config.json'
