name: Check Markdown Links

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.5'
          cache: 'npm'

      - name: Check markdown links
        run: |
          npm ci
          npm run test

      - id: website-bump
        if: github.ref == 'refs/heads/main' && github.repository == 'commonhaus/foundation-draft'
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_PUBLISH_PAT }}
        run: |
          gh workflow run -R commonhaus/commonhaus.github.io gh-pages.yml