name: Push activity to commonhaus.github.io

on:
  discussion:

  pull_request_target:
    types: [opened, edited, reopened, closed]
    paths-ignore:
      - '.*'
      - 'elections'
      - 'templates'

  push:
    branches:
      - main
    paths-ignore:
      - '.*'
      - 'elections'
      - 'templates'

  workflow_dispatch:

permissions: {}

jobs:
  update-website:
    runs-on: ubuntu-latest
    if: github.repository == 'commonhaus/foundation'
    permissions:
      actions: read
    steps:
    - name: Bump website
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_PUBLISH_PAT }}
      run: |
        gh workflow run -R commonhaus/commonhaus.github.io update-content.yml

