name: Push Voting activity to commonhaus.github.io

on:
  discussion_comment:
  issue_comment:

permissions: {}

jobs:
  update-vote:
    runs-on: ubuntu-latest
    if: github.repository == 'commonhaus/foundation'
    permissions:
      actions: read
    steps:
    - name: Bump voting results
      env:
        GH_TOKEN: ${{ secrets.CF_INTERNAL_VOTES }}
      run: |
        gh workflow run -R commonhaus/commonhaus.github.io update-votes.yml
        gh workflow run -R commonhaus/foundation-internal update-votes.yml
